#!/usr/bin/env python3
"""Thin launcher for the installable deez Python module."""

import deez_dots as _deez_module
from deez_dots import *  # noqa: F401,F403


def main() -> None:
    _deez_module.DeezCLI = globals().get("DeezCLI", _deez_module.DeezCLI)
    _deez_module.main()


def run_entrypoint() -> None:
    _deez_module.DeezCLI = globals().get("DeezCLI", _deez_module.DeezCLI)
    _deez_module.run_entrypoint()


if __name__ == "__main__":
    run_entrypoint()
